name: FromDoppler

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main", "INT"]
    tags:
      - v*.*.*

jobs:
  fromdoppler:
    name: Conventions
    uses: FromDoppler/.github/.github/workflows/conventions.yml@main
  dotnet:
    name: .NET
    uses: FromDoppler/.github/.github/workflows/dotnet.yml@main
  docker:
    if: ${{ github.event_name == 'push' }}
    name: Docker
    uses: FromDoppler/.github/.github/workflows/continuous-delivery-dockerfile.yml@main
    secrets: inherit
    with:
      dockerfile-path: "Doppler.EasyNetQ.HosepipeWorker/Dockerfile"
      docker-image-name: "doppler-easynetq-hosepipeworker"
